//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аббревиатура.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить факультет.
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasp.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудитория.
        /// </summary>
        public static string Auditorium {
            get {
                return ResourceManager.GetString("Auditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер аудитории.
        /// </summary>
        public static string AuditoriumCode {
            get {
                return ResourceManager.GetString("AuditoriumCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид аудитории.
        /// </summary>
        public static string AuditoriumKind {
            get {
                return ResourceManager.GetString("AuditoriumKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список видов аудиторий.
        /// </summary>
        public static string AuditoriumKindList {
            get {
                return ResourceManager.GetString("AuditoriumKindList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование вида.
        /// </summary>
        public static string AuditoriumKindName {
            get {
                return ResourceManager.GetString("AuditoriumKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список аудиторий.
        /// </summary>
        public static string AuditoriumList {
            get {
                return ResourceManager.GetString("AuditoriumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корпус.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список корпусов.
        /// </summary>
        public static string BuildingList {
            get {
                return ResourceManager.GetString("BuildingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название корпуса.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вместимость.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очищение....
        /// </summary>
        public static string Clearing {
            get {
                return ResourceManager.GetString("Clearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите очистку.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество занятий.
        /// </summary>
        public static string CountOfClass {
            get {
                return ResourceManager.GetString("CountOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество недель.
        /// </summary>
        public static string CountOfWeeks {
            get {
                return ResourceManager.GetString("CountOfWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление....
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежность к кафедре.
        /// </summary>
        public static string DepartmentAttachment {
            get {
                return ResourceManager.GetString("DepartmentAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кафедр.
        /// </summary>
        public static string DepartmentList {
            get {
                return ResourceManager.GetString("DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование кафедры.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедры в составе института.
        /// </summary>
        public static string DepartmentsInFaculty {
            get {
                return ResourceManager.GetString("DepartmentsInFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дифф. зачет.
        /// </summary>
        public static string DiffGrade {
            get {
                return ResourceManager.GetString("DiffGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплина.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список дисциплин.
        /// </summary>
        public static string DisciplineList {
            get {
                return ResourceManager.GetString("DisciplineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование дисциплины.
        /// </summary>
        public static string DisciplineName {
            get {
                return ResourceManager.GetString("DisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебный план по неделям.
        /// </summary>
        public static string DisciplinePlanByWeeks {
            get {
                return ResourceManager.GetString("DisciplinePlanByWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дисциплины.
        /// </summary>
        public static string DisciplineType {
            get {
                return ResourceManager.GetString("DisciplineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деление на подгруппы.
        /// </summary>
        public static string DivideToSubGroups {
            get {
                return ResourceManager.GetString("DivideToSubGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных.
        /// </summary>
        public static string EditingData {
            get {
                return ResourceManager.GetString("EditingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экзамен.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Институт.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежность к институту.
        /// </summary>
        public static string FacultyAttachment {
            get {
                return ResourceManager.GetString("FacultyAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список институтов.
        /// </summary>
        public static string FacultyList {
            get {
                return ResourceManager.GetString("FacultyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование Института.
        /// </summary>
        public static string FacultyName {
            get {
                return ResourceManager.GetString("FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИКТИБ.
        /// </summary>
        public static string funny_institut {
            get {
                return ResourceManager.GetString("funny_institut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string funny_userok {
            get {
                return ResourceManager.GetString("funny_userok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сгенерировать.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачет.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование группы.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список групп.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество часов.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение.
        /// </summary>
        public static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        public static string InvalidEmpty {
            get {
                return ResourceManager.GetString("InvalidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение аббревиатуры.
        /// </summary>
        public static string InvalidFacultyCode {
            get {
                return ResourceManager.GetString("InvalidFacultyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение названия института.
        /// </summary>
        public static string InvalidFacultyName {
            get {
                return ResourceManager.GetString("InvalidFacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно соответствовать формату &quot;Фамилия Имя Отчество&quot;.
        /// </summary>
        public static string InvalidTeacherName {
            get {
                return ResourceManager.GetString("InvalidTeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторные работы.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string Lecture {
            get {
                return ResourceManager.GetString("Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация.
        /// </summary>
        public static string MainInformation {
            get {
                return ResourceManager.GetString("MainInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных элементов.
        /// </summary>
        public static string NoItemsAvailable {
            get {
                return ResourceManager.GetString("NoItemsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не выбрано.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент не реализовано.
        /// </summary>
        public static string NotImplementedForNow {
            get {
                return ResourceManager.GetString("NotImplementedForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занятость.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип аудитории.
        /// </summary>
        public static string Placeholder_AuditoriumKind {
            get {
                return ResourceManager.GetString("Placeholder_AuditoriumKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер аудитории.
        /// </summary>
        public static string Placeholder_AuditoriumNumber {
            get {
                return ResourceManager.GetString("Placeholder_AuditoriumNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название корпуса.
        /// </summary>
        public static string Placeholder_BuildingName {
            get {
                return ResourceManager.GetString("Placeholder_BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факультет.
        /// </summary>
        public static string Placeholder_FacultyCode {
            get {
                return ResourceManager.GetString("Placeholder_FacultyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное название факультета.
        /// </summary>
        public static string Placeholder_FacultyName {
            get {
                return ResourceManager.GetString("Placeholder_FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практические занятия.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание по парам.
        /// </summary>
        public static string ScheduleByScheduleItem {
            get {
                return ResourceManager.GetString("ScheduleByScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат расписания.
        /// </summary>
        public static string ScheduleFormat {
            get {
                return ResourceManager.GetString("ScheduleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пара.
        /// </summary>
        public static string ScheduleItem {
            get {
                return ResourceManager.GetString("ScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее кол-во пар.
        /// </summary>
        public static string ScheduleItemsCount {
            get {
                return ResourceManager.GetString("ScheduleItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа, кафедра, курс....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} выбрано.
        /// </summary>
        public static string SelectControl_CountSelectedText {
            get {
                return ResourceManager.GetString("SelectControl_CountSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string SelectControl_DeselectAll {
            get {
                return ResourceManager.GetString("SelectControl_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string SelectControl_SelectAll {
            get {
                return ResourceManager.GetString("SelectControl_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти с помощью.
        /// </summary>
        public static string SignInWith {
            get {
                return ResourceManager.GetString("SignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала семестра.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество студентов.
        /// </summary>
        public static string StudentCount {
            get {
                return ResourceManager.GetString("StudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование под-дисциплины.
        /// </summary>
        public static string SubDisciplineName {
            get {
                return ResourceManager.GetString("SubDisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виды занятий.
        /// </summary>
        public static string SubDisciplines {
            get {
                return ResourceManager.GetString("SubDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип вида занятия.
        /// </summary>
        public static string SubDisciplineType {
            get {
                return ResourceManager.GetString("SubDisciplineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список преподавателей.
        /// </summary>
        public static string TeacherList {
            get {
                return ResourceManager.GetString("TeacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО преподавателя.
        /// </summary>
        public static string TeacherName {
            get {
                return ResourceManager.GetString("TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступно.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала этой пары пересекается с прошлой парой.
        /// </summary>
        public static string Validation_ScheduleItemIntersectsWithPrevious {
            get {
                return ResourceManager.GetString("Validation_ScheduleItemIntersectsWithPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недели.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
    }
}
