//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аббревиатура.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить факультет.
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все пары распределены.
        /// </summary>
        public static string AllClassesScheduled {
            get {
                return ResourceManager.GetString("AllClassesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все преподаватели.
        /// </summary>
        public static string AllTeachers {
            get {
                return ResourceManager.GetString("AllTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasp.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудитория.
        /// </summary>
        public static string Auditorium {
            get {
                return ResourceManager.GetString("Auditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер аудитории.
        /// </summary>
        public static string AuditoriumCode {
            get {
                return ResourceManager.GetString("AuditoriumCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид аудитории.
        /// </summary>
        public static string AuditoriumKind {
            get {
                return ResourceManager.GetString("AuditoriumKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список видов аудиторий.
        /// </summary>
        public static string AuditoriumKindList {
            get {
                return ResourceManager.GetString("AuditoriumKindList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование вида.
        /// </summary>
        public static string AuditoriumKindName {
            get {
                return ResourceManager.GetString("AuditoriumKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список аудиторий.
        /// </summary>
        public static string AuditoriumList {
            get {
                return ResourceManager.GetString("AuditoriumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корпус.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список корпусов.
        /// </summary>
        public static string BuildingList {
            get {
                return ResourceManager.GetString("BuildingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название корпуса.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вместимость.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите аудиторию.
        /// </summary>
        public static string ChooseAuditorium {
            get {
                return ResourceManager.GetString("ChooseAuditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите группу.
        /// </summary>
        public static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите предметы для экспорта.
        /// </summary>
        public static string ChooseItemsForExport {
            get {
                return ResourceManager.GetString("ChooseItemsForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите расписание.
        /// </summary>
        public static string ChooseSchedule {
            get {
                return ResourceManager.GetString("ChooseSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите преподавателя.
        /// </summary>
        public static string ChooseTeacher {
            get {
                return ResourceManager.GetString("ChooseTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to занятие.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очищение....
        /// </summary>
        public static string Clearing {
            get {
                return ResourceManager.GetString("Clearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите действие.
        /// </summary>
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите очистку.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать для всех групп.
        /// </summary>
        public static string CopyForAllGroups {
            get {
                return ResourceManager.GetString("CopyForAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать с .
        /// </summary>
        public static string CopyFrom {
            get {
                return ResourceManager.GetString("CopyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать с недели.
        /// </summary>
        public static string CopyFromWeek {
            get {
                return ResourceManager.GetString("CopyFromWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество занятий.
        /// </summary>
        public static string CountOfClass {
            get {
                return ResourceManager.GetString("CountOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество недель.
        /// </summary>
        public static string CountOfWeeks {
            get {
                return ResourceManager.GetString("CountOfWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление....
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежность к кафедре.
        /// </summary>
        public static string DepartmentAttachment {
            get {
                return ResourceManager.GetString("DepartmentAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кафедр.
        /// </summary>
        public static string DepartmentList {
            get {
                return ResourceManager.GetString("DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование кафедры.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедры в составе института.
        /// </summary>
        public static string DepartmentsInFaculty {
            get {
                return ResourceManager.GetString("DepartmentsInFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дифф. зачет.
        /// </summary>
        public static string DiffGrade {
            get {
                return ResourceManager.GetString("DiffGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплина.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список дисциплин.
        /// </summary>
        public static string DisciplineList {
            get {
                return ResourceManager.GetString("DisciplineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование дисциплины.
        /// </summary>
        public static string DisciplineName {
            get {
                return ResourceManager.GetString("DisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебный план по неделям.
        /// </summary>
        public static string DisciplinePlanByWeeks {
            get {
                return ResourceManager.GetString("DisciplinePlanByWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дисциплины.
        /// </summary>
        public static string DisciplineType {
            get {
                return ResourceManager.GetString("DisciplineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деление на подгруппы.
        /// </summary>
        public static string DivideToSubGroups {
            get {
                return ResourceManager.GetString("DivideToSubGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование данных.
        /// </summary>
        public static string EditingData {
            get {
                return ResourceManager.GetString("EditingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экзамен.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата экспорта:.
        /// </summary>
        public static string ExportDate {
            get {
                return ResourceManager.GetString("ExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Институт.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежность к институту.
        /// </summary>
        public static string FacultyAttachment {
            get {
                return ResourceManager.GetString("FacultyAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список институтов.
        /// </summary>
        public static string FacultyList {
            get {
                return ResourceManager.GetString("FacultyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование Института.
        /// </summary>
        public static string FacultyName {
            get {
                return ResourceManager.GetString("FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распределить с конца.
        /// </summary>
        public static string FillFromEnd {
            get {
                return ResourceManager.GetString("FillFromEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распределить с начала.
        /// </summary>
        public static string FillFromStart {
            get {
                return ResourceManager.GetString("FillFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятница.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИКТИБ.
        /// </summary>
        public static string funny_institut {
            get {
                return ResourceManager.GetString("funny_institut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string funny_userok {
            get {
                return ResourceManager.GetString("funny_userok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сгенерировать.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачет.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование группы.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список групп.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество часов.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импортируем.
        /// </summary>
        public static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение.
        /// </summary>
        public static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        public static string InvalidEmpty {
            get {
                return ResourceManager.GetString("InvalidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение аббревиатуры.
        /// </summary>
        public static string InvalidFacultyCode {
            get {
                return ResourceManager.GetString("InvalidFacultyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение названия института.
        /// </summary>
        public static string InvalidFacultyName {
            get {
                return ResourceManager.GetString("InvalidFacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно соответствовать формату &quot;Фамилия Имя Отчество&quot;.
        /// </summary>
        public static string InvalidTeacherName {
            get {
                return ResourceManager.GetString("InvalidTeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип проведения.
        /// </summary>
        public static string IsParallelType {
            get {
                return ResourceManager.GetString("IsParallelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуально.
        /// </summary>
        public static string IsParallelType_Individual {
            get {
                return ResourceManager.GetString("IsParallelType_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток.
        /// </summary>
        public static string IsParallelType_Parallel {
            get {
                return ResourceManager.GetString("IsParallelType_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторные работы.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string Lecture {
            get {
                return ResourceManager.GetString("Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация.
        /// </summary>
        public static string MainInformation {
            get {
                return ResourceManager.GetString("MainInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понедельник.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных элементов.
        /// </summary>
        public static string NoItemsAvailable {
            get {
                return ResourceManager.GetString("NoItemsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не выбрано.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент не реализовано.
        /// </summary>
        public static string NotImplementedForNow {
            get {
                return ResourceManager.GetString("NotImplementedForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занятость.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип аудитории.
        /// </summary>
        public static string Placeholder_AuditoriumKind {
            get {
                return ResourceManager.GetString("Placeholder_AuditoriumKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер аудитории.
        /// </summary>
        public static string Placeholder_AuditoriumNumber {
            get {
                return ResourceManager.GetString("Placeholder_AuditoriumNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название корпуса.
        /// </summary>
        public static string Placeholder_BuildingName {
            get {
                return ResourceManager.GetString("Placeholder_BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факультет.
        /// </summary>
        public static string Placeholder_FacultyCode {
            get {
                return ResourceManager.GetString("Placeholder_FacultyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное название факультета.
        /// </summary>
        public static string Placeholder_FacultyName {
            get {
                return ResourceManager.GetString("Placeholder_FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практические занятия.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования к аудиториям.
        /// </summary>
        public static string PreferencesToAuditorium {
            get {
                return ResourceManager.GetString("PreferencesToAuditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать праздник.
        /// </summary>
        public static string RemoveWeekendDay {
            get {
                return ResourceManager.GetString("RemoveWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить все.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на поиск.
        /// </summary>
        public static string ReturnToSearch {
            get {
                return ResourceManager.GetString("ReturnToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суббота.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание по парам.
        /// </summary>
        public static string ScheduleByScheduleItem {
            get {
                return ResourceManager.GetString("ScheduleByScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат расписания.
        /// </summary>
        public static string ScheduleFormat {
            get {
                return ResourceManager.GetString("ScheduleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пара.
        /// </summary>
        public static string ScheduleItem {
            get {
                return ResourceManager.GetString("ScheduleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее кол-во пар.
        /// </summary>
        public static string ScheduleItemsCount {
            get {
                return ResourceManager.GetString("ScheduleItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа, кафедра, курс....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} выбрано.
        /// </summary>
        public static string SelectControl_CountSelectedText {
            get {
                return ResourceManager.GetString("SelectControl_CountSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string SelectControl_DeselectAll {
            get {
                return ResourceManager.GetString("SelectControl_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string SelectControl_SelectAll {
            get {
                return ResourceManager.GetString("SelectControl_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность сессии в неделях.
        /// </summary>
        public static string SessionDurationInWeeks {
            get {
                return ResourceManager.GetString("SessionDurationInWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя начала сессии.
        /// </summary>
        public static string SessionStartWeek {
            get {
                return ResourceManager.GetString("SessionStartWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выставить автоматически.
        /// </summary>
        public static string SetWeekendAutomatic {
            get {
                return ResourceManager.GetString("SetWeekendAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить праздник.
        /// </summary>
        public static string SetWeekendDay {
            get {
                return ResourceManager.GetString("SetWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти с помощью.
        /// </summary>
        public static string SignInWith {
            get {
                return ResourceManager.GetString("SignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала семестра.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество студентов.
        /// </summary>
        public static string StudentCount {
            get {
                return ResourceManager.GetString("StudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование вида занятия.
        /// </summary>
        public static string SubDisciplineName {
            get {
                return ResourceManager.GetString("SubDisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виды занятий.
        /// </summary>
        public static string SubDisciplines {
            get {
                return ResourceManager.GetString("SubDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип вида занятия.
        /// </summary>
        public static string SubDisciplineType {
            get {
                return ResourceManager.GetString("SubDisciplineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подгруппа.
        /// </summary>
        public static string SubGroup {
            get {
                return ResourceManager.GetString("SubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to п/г.
        /// </summary>
        public static string SubGroupAbbreviation {
            get {
                return ResourceManager.GetString("SubGroupAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресенье.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель занят в это время.
        /// </summary>
        public static string TeacherBusyAtThisTime {
            get {
                return ResourceManager.GetString("TeacherBusyAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель не может провести занятие в это время.
        /// </summary>
        public static string TeacherImpossibleThisTime {
            get {
                return ResourceManager.GetString("TeacherImpossibleThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список преподавателей.
        /// </summary>
        public static string TeacherList {
            get {
                return ResourceManager.GetString("TeacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО преподавателя.
        /// </summary>
        public static string TeacherName {
            get {
                return ResourceManager.GetString("TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели или группы не введены.
        /// </summary>
        public static string TeacherOrGroupNotSelected {
            get {
                return ResourceManager.GetString("TeacherOrGroupNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпочтения преподавателей.
        /// </summary>
        public static string TeacherPreferences {
            get {
                return ResourceManager.GetString("TeacherPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четверг.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить/Снять праздник.
        /// </summary>
        public static string ToggleWeekend {
            get {
                return ResourceManager.GetString("ToggleWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступно.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нераспределённые занятия.
        /// </summary>
        public static string UnscheduledClasses {
            get {
                return ResourceManager.GetString("UnscheduledClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нежелательно.
        /// </summary>
        public static string Unwanted {
            get {
                return ResourceManager.GetString("Unwanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нежелательные пары.
        /// </summary>
        public static string UnwantedClasses {
            get {
                return ResourceManager.GetString("UnwantedClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала этой пары пересекается с прошлой парой.
        /// </summary>
        public static string Validation_ScheduleItem_IntersectsWithPrevious {
            get {
                return ResourceManager.GetString("Validation_ScheduleItem_IntersectsWithPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия выходит за границы семестра.
        /// </summary>
        public static string Validation_SessionStartWeek_SessionOverheadsSemester {
            get {
                return ResourceManager.GetString("Validation_SessionStartWeek_SessionOverheadsSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среда.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выходные.
        /// </summary>
        public static string Weekends {
            get {
                return ResourceManager.GetString("Weekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недели.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недели по.
        /// </summary>
        public static string WeekTo {
            get {
                return ResourceManager.GetString("WeekTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без подгрупп.
        /// </summary>
        public static string WithoutSubGroups {
            get {
                return ResourceManager.GetString("WithoutSubGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С подгруппами.
        /// </summary>
        public static string WithSubGroups {
            get {
                return ResourceManager.GetString("WithSubGroups", resourceCulture);
            }
        }
    }
}
